### ISSUE TITLE
Travis-ci: build is failing on AMD64.

### ISSUE THREAD

**Issue by sanjaymsh** [headius/invokebinder#11]
Hi,

I was just testing the build on travis-ci. But its failing with below error:
"
Worker information
0.16s0.01s0.00s0.01s
system_info
Build system information
0.02s0.01s0.64s0.23s0.05s0.00s0.04s0.00s0.01s0.01s0.01s0.01s0.01s0.00s0.00s0.02s0.00s0.01s0.36s0.00s0.00s0.00s0.01s0.00s0.10s0.01s0.85s0.00s0.00s6.03s0.00s2.93s0.00s2.56s
docker_mtu
resolvconf
install_jdk
Installing oraclejdk9
11.98s$ travis_apt_get_update
Installing APT Packages
0.42s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install oracle-java9-installer
Reading package lists...
Building dependency tree...
Reading state information...
Package oracle-java9-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'oracle-java9-installer' has no installation candidate
apt-get.diagnostics
apt-get install failed
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install oracle-java9-installer" failed and exited with 100 during .
Your build has been stopped.
"

Please have a look on this.

Thanks !!

**Comment by headius** [comment]
Yeah I just noticed this myself today. Will look into it.

**Comment by headius** [comment]
With a fix to use openjdk11 and update the bnd plugin, we are green again: https://travis-ci.org/github/headius/invokebinder/builds/737823979

**Comment by sanjaymsh** [comment]
Thanks !!
