### ISSUE TITLE
OSGify invokebinder

### ISSUE THREAD

**Issue by sakno** [headius/invokebinder#6]
Add `maven-bundle-plugin` to POM and allow to install and use invokebinder in OSGi environment

**Comment by headius** [comment]
PR?

**Comment by sakno** [comment]
What you mean? I just want to use invokebinder in OSGi environment.

**Comment by headius** [comment]
PR = Pull Request... I don't know the proper way to add `maven-bundle-plugin` to the POM and humbly request your assistance :-)

**Comment by sakno** [comment]
#7

**Comment by headius** [comment]
Fixed by #7.
